name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clearly describe the bug and its impact
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What was supposed to happen?
      placeholder: Expected result...
    validations:
      required: false

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What actually happened?
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Describe how to reproduce the bug
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, browser, device, version, etc.
      placeholder: e.g. Windows 11, Chrome 123, Desktop, API v2.3
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Additional Context / Logs
      description: Paste error logs, screenshots, or any extra info
      placeholder: Logs or context...
    validations:
      required: false
